-- The cached morning briefing, one row per workspace per day.
--
-- Generated by drizzle-kit, then edited by hand for two reasons:
--
--  1. The generator also emitted CREATE TABLE "waitlist". That table already
--     exists — 0024_waitlist.sql created it without refreshing the snapshot, so
--     drizzle believed it was still missing. Left in, this migration would have
--     failed on `relation "waitlist" already exists` and taken the briefings
--     table down with it. The 0025 snapshot records both tables, so the drift
--     ends here.
--
--  2. Tenant isolation is not generated. A new tenant table is not finished
--     until it has the grant, FORCE RLS, and the policy below — `enableRLS()`
--     alone leaves a table that denies everything, and a grant added later
--     without the policy would expose every workspace's briefing to every other.

CREATE TABLE "briefings" (
	"organization_id" uuid NOT NULL,
	"workspace_id" uuid NOT NULL,
	"day" date NOT NULL,
	"kind" text DEFAULT 'morning' NOT NULL,
	"headline" text NOT NULL,
	"narrative" text NOT NULL,
	"confidence" integer NOT NULL,
	"evidence_count" integer DEFAULT 0 NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "briefings_workspace_id_day_pk" PRIMARY KEY("workspace_id","day")
);
--> statement-breakpoint
ALTER TABLE "briefings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "briefings" ADD CONSTRAINT "briefings_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "briefings" ADD CONSTRAINT "briefings_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "briefings_organization_id_idx" ON "briefings" USING btree ("organization_id");
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON briefings TO app_tenant;
--> statement-breakpoint
ALTER TABLE briefings FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY briefings_tenant_isolation ON briefings FOR ALL TO app_tenant USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
